name: Swift

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: fastlane buildLane
    - name: Upload build
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: derivedData/Build/Products/Debug-iphonesimulator/GithubActions.app
    - name: Upload runner
      uses: actions/upload-artifact@v1
      with:
        name: runner
        path: derivedData/Build/Products/Debug-iphonesimulator/GithubActionsUITests-Runner.app

  unitTests:
    needs: build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download build
      uses: actions/download-artifact@v1
      with:
        name: build
        path: derivedData/Build/Products/Debug-iphonesimulator/GithubActions.app
    - name: Run unit tests
      run: fastlane unitTestLane

  uiTests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download build
      uses: actions/download-artifact@v1
      with:
        name: build
        path: derivedData/Build/Products/Debug-iphonesimulator/GithubActions.app
    - name: Download runner
      uses: actions/download-artifact@v1
      with:
        name: runner
        path: derivedData/Build/Products/Debug-iphonesimulator/GithubActionsUITests-Runner.app
    - name: Run UI tests
      run: fastlane uiTestLane